### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by ChenglongSong** [He-Xiang-best/Facial-Expression-Recognition#1]
您好，我想问下
①在VGG中是否需要代码原型，参考您的代码最后的运行结果中一直都是angry，这个是什么原因导致的呀
②您的模型对比代码中，是只需要修改训练集和验证集的路径吗

**Comment by hexiang10** [comment]
①：你可以用我训练好提供的模型，也可以用自己的，我的代码以及相关总结是基于我开发过程的，可以有写纰漏，具体哪里不同，哪里有问题，还是自己去发现，可以看看相关教程；
②：有些我写了修改路径的，如果用的话，就要进行修改，我还没有非常详细的检查，不知道还有没其他要修改的，但自己没标清楚你在开发过程中跟进检查就好；
补充：
不久前也弄到了一份相关的教程，有时间学习后，会对现有的代码进行重构和补充。

**Comment by AZyfen** [comment]
> 您好，我想问下 ①在VGG中是否需要代码原型，参考您的代码最后的运行结果中一直都是angry，这个是什么原因导致的呀 ②您的模型对比代码中，是只需要修改训练集和验证集的路径吗

请问，这个问题，您找到解决方法了吗？是什么原因导致的呀？

**Comment by hexiang10** [comment]
问：您的模型对比代码中，是只需要修改训练集和验证集的路径吗？
答：还需要模型（自己训练的或者是现有训练好的）

**Comment by ChenglongSong** [comment]
请问VGG_Model_template.py文件是自己写的还是已有的呀

**Comment by ChenglongSong** [comment]
请问VGG_Model_template.py文件是自己写的还是已有的呀

**Comment by ChenglongSong** [comment]
> 

还没解决

**Comment by ChenglongSong** [comment]
> > 您好，我想问下 ①在VGG中是否需要代码原型，参考您的代码最后的运行结果中一直都是angry，这个是什么原因导致的呀 ②您的模型对比代码中，是只需要修改训练集和验证集的路径吗
> 
> 请问，这个问题，您找到解决方法了吗？是什么原因导致的呀？

还没解决

**Comment by hexiang10** [comment]
> 请问VGG_Model_template.py文件是自己写的还是已有的呀

你看看有没少下载什么东西：

本项目的数据集文件下载地址：https://download.csdn.net/download/HXBest/64847238

本项目的训练模型文件下载地址：https://download.csdn.net/download/HXBest/64955910

**Comment by HYWang-st** [comment]
> 您好，我想问下 ①在VGG中是否需要代码原型，参考您的代码最后的运行结果中一直都是angry，这个是什么原因导致的呀 ②您的模型对比代码中，是只需要修改训练集和验证集的路径吗

在VGG代码中，使用了torchvision.datasets.ImageFolder来加载训练和验证集数据。这个函数假设数据按照文件夹进行组织，每个文件夹代表一个类别。然而，根据该项目的描述，数据集中只有一个文件夹。导致了标签错误，即始终默认为0序号--angry
