### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by ChenglongSong** [He-Xiang-best/Facial-Expression-Recognition#2]
文件是不少的，但是VGG和ResNet模型跑出来多次都结果一直是angry，检查多天代码也没找到问题，请问作者当时跑出来了吗

**Comment by ChenglongSong** [comment]
![Uploading 1%26414LH($3()W~TSN@I]9.png…]()
请问这个路径是什么意思呀？需要改吗？如何更改的呀？

**Comment by ChenglongSong** [comment]
![1%26414LH($3()W~TSN@I 9](https://user-images.githubusercontent.com/90268590/231390700-167ac300-ea80-4d10-b95d-f0a4336e979e.png)
请问这个路径是什么意思呀？需要改吗？如何更改的呀？

**Comment by ChenglongSong** [comment]
![W_)YUNPFUTH{XZ60QIL@$D7](https://user-images.githubusercontent.com/90268590/231403586-cb4c2128-beef-4aeb-9b8c-b0d7378960e5.png)
同时在ResNet模型中也发现了在模型文件（ResNet_model_template）中有些报错是关于导入resnet101、34这些语句的，想问一下您当时是怎么解决的

**Comment by hexiang10** [comment]
认真看文档了嘛，VGG和ResNet只提供了实现设计方案噢，没有落地，【Plus】项目会完善内容噢！

**Comment by ChenglongSong** [comment]
奥奥 好的  我是想实现另外两个模型，把这两个模型落地，请问有什么资源和资料可以推荐的吗

**Comment by hexiang10** [comment]
一些学习资料在note分支有，资源你可以去bilibili找一找，参考符合你需求的设计

**Comment by Mxy0331** [comment]
> 文件是不少的，但是VGG和ResNet模型跑出来多次都结果一直是angry，检查多天代码也没找到问题，请问作者当时跑出来了吗

请问您解决这个问题了吗，我也是训练vgg的时候，准确率都为100%，而且测试后均为angry。

**Comment by HYWang-st** [comment]
> 文件是不少的，但是VGG和ResNet模型跑出来多次都结果一直是angry，检查多天代码也没找到问题，请问作者当时跑出来了吗

在VGG与ResNet代码中，使用了torchvision.datasets.ImageFolder来加载训练和验证集数据。这个函数假设数据按照文件夹进行组织，每个文件夹代表一个类别。然而，根据该项目的描述，数据集中只有一个文件夹。导致了标签错误，即始终默认为0序号--angry

**Comment by xiaoxiongsyy** [comment]
我用cnn模型跑出来结果也一直是angry是为什么
